apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tal-statefulset
  labels:
    app: taltestapp
spec:
  serviceName: tal-service
  replicas: 1
  selector:
    matchLabels:
      app: taltestapp
  template:
    metadata:
      labels:
        app: taltestapp
    spec:
      containers:
      - name: tal-container
        image: talk474747/talteststuff:tal-study-gitops
        imagePullPolicy: Always  # Ensure the image is always pulled
        env:
        - name: BACKGROUND_COLOR
          value: "blue"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tal-service
  labels:
    app: taltestapp
spec:
  selector:
    app: taltestapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
